version: '3'

services:
  app:
    build:
      context: ./nodejs
    container_name: app_node
    entrypoint: dockerize --wait tcp://db_node:3306 -timeout 40s node src/index.js
    tty: true
    networks:
      - nodenet
    depends_on: 
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_node
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - nodenet
  proxy:
      build:
        context: ./proxy
      container_name: proxy_node
      ports:
        - 8080:80
      networks:
      - nodenet
networks:
  nodenet:
    driver: bridge